blank_issues_enabled: false
contact_links:
  - name: View documentation ğŸ“š
    url: https://usehooks-ts.com/
    about: Check out the official docs for answers to common questions.
  - name: Feature requests ğŸ’¡
    url: https://github.com/juliencrn/usehooks-ts/discussions/categories/ideas
    about: Suggest a new React hook idea.
  - name: Questions ğŸ’­
    url: https://github.com/juliencrn/usehooks-ts/discussions/categories/help
    about: Need support with a React hook problem? Open up a help request.
  - name: Donate â¤ï¸
    url: https://github.com/sponsors/juliencrn
    about: Love usehooks-ts? Show your support by donating today!
